services:
  database:
    image: postgres:16.4
    environment:
      POSTGRES_USER: "test-user"
      POSTGRES_PASSWORD: "test-password"
      POSTGRES_DB: "tracker-tv"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

  db-migration:
    build:
      context: .
      dockerfile: Dockerfile.db-migration
    depends_on:
      database:
        condition: service_healthy
    environment:
      GOOSE_DBSTRING: "postgres://test-user:test-password@database:5432/tracker-tv"

volumes:
  data:
